/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/app/theme/nook.ts
 * Command: astryx theme build src/app/theme/nook.ts --out src/app/theme/nook.css
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

/// <reference path="./nook.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const nookTheme: DefinedTheme;
